### ISSUE TITLE
fread dependency on "curl" package

### ISSUE THREAD

**Issue by brianhigh** [eddiekasner/PNASHR-Workshop#2]
In severe_injury.R, there was code that was specific to SPH server, not using fread but instead using a local file. This can be avoided by installing the "curl" package, which appears to be a dependency of fread. For some reason, installing data.table does not take care of this dependency. The script was modified accordingly in commit #2

**Comment by brianhigh** [comment]
FYI - The reason why I think data.table does not list "curl" in its package dependencies is because fread only uses "curl" for "https" URLs. This can be demonstrated as follows:

```
library(curl)
# Error in library(curl) : there is no package called ‘curl’

library(data.table)
# data.table 1.13.2 using 20 threads (see ?getDTthreads).  Latest news: r-datatable.com

df <- fread("http://www.osha.gov/severeinjury/xml/severeinjury.csv", verbose = F)
# trying URL 'http://www.osha.gov/severeinjury/xml/severeinjury.csv'
# downloaded 25.7 MB

df <- fread("https://www.osha.gov/severeinjury/xml/severeinjury.csv", verbose = F)
# Error in fread("https://www.osha.gov/severeinjury/xml/severeinjury.csv",  : 
#   Input URL requires https:// connection for which fread() requires 'curl' package which cannot be found. Please install 'curl' using # 'install.packages('curl')'.

install.packages("curl")
# ...
#  curl installed

df <- fread("https://www.osha.gov/severeinjury/xml/severeinjury.csv", verbose = F)
#  [100%] Downloaded 9270576 bytes...
```

**Comment by elaustin** [comment]
Thanks Brian, that's a tricky situation. I do think that some of these
inconsistencies in R packages is what makes on-boarding new users most
challenging.

Elena

**Comment by brianhigh** [comment]
True, R can be very inconsistent, especially between packages. From a reproducibility standpoint, if we adopted the practice that "curl" was listed in the p_load (or library) call along with "data.table" for any script that loads data from https URLs with fread, then it would cover new users as well as others. That is, I think we can learn from this to improve our scripts for all situations, not just for new users. And the general rule would be to know (and load explicitly) which packages are being used by our scripts, including their dependencies. This particular case is unusual in that data.table does not list curl as a dependency but should, in my opinion.
